### PR TITLE
May 2019 Update

### PR DESCRIPTION
**Pull request by deltadan**
This the PR for the BCDR May Update.  This includes a move to using Availablity Zones and Frontdoor.  The planned change for the Powershell would have added about 3 hours of work for the student and provide no value, so I didn't move forward with that change.

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
SME feedback from Rochak Mittal (via email):

I have few important feedback for overall HOL, Can we incorporate them before next update. 

1.	It is unclear why we are talking about Solution - Environment: On-premises (migrate to Azure) in the Business continuity workshop . Migration scenario is sprinkled in the lab tasks and break overall flow. 
2.	In the IaaS VM creation we are still using un-managed disk. The HOL should get updated to be managed disk as that is the recommended way
3.	In the step by step HOL – in step “Create Azure recovery services vault”  we refer to “backup and site recovery (OMS)”. As OMS has been retired the service search should be with “Recovery Services vault”
4.	We should add file/SQL backup and restore in the solutions and remove migration if the lab is becoming long. 

Regards
Rochak

**Comment by ChongRX78** [comment]
@deltadan, any comments to what Rochak has proposed?

**Comment by DawnmarieDesJardins** [comment]
@deltadan @ChongRX78 
Hi Dan,
Please provide your guidance to the comments above.
Thanks, Dawnmarie

**Comment by deltadan** [comment]
Thank you very much for your feedback on this MCW!

1.	 We understand at first glance that migrating application is confusing for this WDS.  The reason for the migration is that the application currently has no BCDR strategy.  By migrating the application to the cloud the student learns that sometimes it is best to Lift and Shift and application in order to put a BCDR strategy in place.  In only a few steps they have resolved a major business issue.
2.	The IaaS VMs are using managed disks throughout the lab for this update.  If you noted something different please provide further details.
3.	The link in the Azure portal still uses the name OMS, so to ensure that the students are confused we are using the same name and screenshots.
4.	A SQL backup and restore is a great idea of this lab, but currently, there isn’t a plan to add this step.  We should put this in the queue as an update or this could be done as a pull request to the MCW via the open source project.

**Comment by deltadan** [comment]
@DawnmarieDesJardins I have continued to test the MCW and found a final issue that I wanted to fix based on some stability issues were saw during the development.  The issue has been resolved and it ready for this PR to be completed.

**Pull request merged**
